# Generated by Django 4.2.7 on 2025-05-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_tutorservice_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantproduct',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentproduct',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tutorservice',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
