# Generated by Django 4.2.7 on 2025-05-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_merchantproduct_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantproduct',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used_like_new', 'Used - Like New'), ('used_good', 'Used - Good'), ('used_fair', 'Used - Fair')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='tutorservice',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used_like_new', 'Used - Like New'), ('used_good', 'Used - Good'), ('used_fair', 'Used - Fair')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentproduct',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used_like_new', 'Used - Like New'), ('used_good', 'Used - Good'), ('used_fair', 'Used - Fair')], default='new', max_length=20),
        ),
    ]
